'use client';

import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';

type Rate = { rates: Record<'24' | '22' | '18', number>; effectiveAt: string; updatedAt: string };
export default function AdminPage() {
  const [loggedIn, setLoggedIn] = useState(false); const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [rates, setRates] = useState({ '24': '', '22': '', '18': '' }); const [current, setCurrent] = useState<Rate | null>(null); const [message, setMessage] = useState('');
  async function login(event: FormEvent) { event.preventDefault(); setMessage(''); const response = await fetch('/api/admin/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username, password }) }); const data = await response.json().catch(() => ({})); if (!response.ok) return setMessage(data.error ?? 'Unable to sign in.'); setLoggedIn(true); loadRate(); }
  async function loadRate() { const response = await fetch('/api/admin/rate'); if (response.ok) { const data = await response.json() as Rate; setCurrent(data); setRates({ '24': String(data.rates['24']), '22': String(data.rates['22']), '18': String(data.rates['18']) }); } }
  async function save(event: FormEvent) { event.preventDefault(); const response = await fetch('/api/admin/rate', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ rates }) }); setMessage(response.ok ? 'Rates updated. The public calculator is live with these values.' : 'Could not update the rates.'); if (response.ok) loadRate(); }
  useEffect(() => { if (loggedIn) loadRate(); }, [loggedIn]);
  return <main className="admin-page"><Link className="admin-brand" href="/">PKV GOLD <span>RATE CONTROL</span></Link>{!loggedIn ? <form className="admin-card" onSubmit={login}><p className="kicker">PRIVATE ACCESS</p><h1>Gold rates.</h1><p>Sign in to manage the live per-gram rates for 24K, 22K and 18K gold.</p><label>Username<input value={username} onChange={(e) => setUsername(e.target.value)} autoComplete="username" required /></label><label>Password<input value={password} onChange={(e) => setPassword(e.target.value)} type="password" autoComplete="current-password" required /></label><button className="btn btn-gold">LOG IN <b>→</b></button>{message && <small className="admin-message">{message}</small>}</form> : <form className="admin-card" onSubmit={save}><p className="kicker">ADMIN / LIVE RATES</p><h1>Gold rate control.</h1><p>Set the rate per gram used by the public calculator for each available purity.</p>{(['24','22','18'] as const).map(karat=><label key={karat}>{karat}K rate per gram<input value={rates[karat]} onChange={(e) => setRates({...rates,[karat]:e.target.value})} type="number" min="1" step="0.01" required /></label>)}<button className="btn btn-gold">SAVE RATES <b>→</b></button>{current && <div className="admin-meta"><span>24K <b>₹{current.rates['24'].toLocaleString('en-IN')}</b></span><span>22K <b>₹{current.rates['22'].toLocaleString('en-IN')}</b></span><span>18K <b>₹{current.rates['18'].toLocaleString('en-IN')}</b></span><span>Last updated <b>{new Date(current.updatedAt).toLocaleString('en-IN')}</b></span></div>}{message && <small className="admin-message">{message}</small>}</form>}</main>;
}
