'use client';

import { useEffect, useMemo, useState } from 'react';
import { contact, purityOptions } from '@/lib/constants';
import { buildGeneralWhatsAppUrl } from '@/lib/whatsapp';
import { calculateGoldValue, formatIndianRupees } from '@/lib/calculator';
import { jewelleryCategories } from '@/lib/jewellery';
import { HeroValueTransition } from '@/components/motion/HeroValueTransition';
import { AppointmentModal } from '@/components/contact/AppointmentModal';
import { ContactActions } from '@/components/contact/ContactActions';
import { LocationMap } from '@/components/sections/Location/LocationMap';
import { FloatingContactActions } from '@/components/contact/FloatingContactActions';
import heroMediaStyles from '@/components/sections/HomeHeroMedia.module.css';

const faqs = [
  ['How is my gold valued?', 'We assess purity and net gold weight, then apply the current PKV Gold rate for that purity. The final value is explained before you decide.'],
  ['What gold items can I bring?', 'Gold jewellery, old gold, broken pieces, coins, ornaments and heirloom pieces can all be assessed.'],
  ['Does the gold rate change daily?', 'Rates are managed by PKV Gold and may change with the market. The public calculator always requests the latest active rate.'],
  ['How is purity checked?', 'Purity is assessed physically at PKV Gold using the appropriate testing process for the item.'],
  ['Is the calculator value final?', 'No. It is an indicative estimate. Final value is confirmed only after physical assessment of purity and net weight.'],
  ['Do I need to visit the branch?', 'Yes, physical assessment at PKV Gold is required for a confirmed valuation.'],
  ['What documents/details are required?', 'Bring the gold you want assessed and a valid phone number so we can explain the next step.'],
  ['How do I contact PKV Gold?', `Call, WhatsApp, or use the enquiry form. We are based in ${contact.locationLabel}.`],
] as const;

export default function Home() {
  const [rate, setRate] = useState<number | null>(null);
  const [karat, setKarat] = useState(22);
  const [weight, setWeight] = useState(12.4);
  const [openFaq, setOpenFaq] = useState(0);
  const [appointmentOpen, setAppointmentOpen] = useState(false);
  const selected = purityOptions.find((item) => item.karat === karat) ?? purityOptions[1];
  const estimate = useMemo(() => rate === null ? null : calculateGoldValue(weight, rate * selected.factor), [rate, weight, selected.factor]);

  useEffect(() => { fetch('/api/rate').then((res) => res.json()).then((data) => setRate(data.rate)).catch(() => undefined); }, []);
  return <div className="site-shell">
    <header className="site-header"><a href="#top" className="brand"><span>PKV GOLD</span><small>GOLD BUYING <i>•</i> VALUATION</small></a><nav className="desktop-nav"><a href="#value">Know your value</a><a href="#gold-we-value">The gold we value</a><a href="#process">How it works</a><a href="#location">Location</a><a href="#contact">Contact</a></nav><a className="btn btn-gold header-cta" href="#value">VALUATE <b>→</b></a></header>
    <main id="top"><HeroValueTransition>
      <section className="hero-light" data-hero-scene><div className="hero-copy" data-hero-copy><p className="kicker">CASH FOR GOLD <span>•</span> {contact.locationLabel.toUpperCase()}</p><h1>Your gold.<br /><em>Your value.</em></h1><p className="hero-lede">A precise, transparent way to understand what the gold you already own may be worth today.</p><div className="hero-actions"><a className="btn btn-gold" href="#value">CALCULATE MY VALUE <b>→</b></a><a className="btn btn-outline" href={buildGeneralWhatsAppUrl()} target="_blank" rel="noopener noreferrer">WHATSAPP PKV GOLD <b>→</b></a><button className="btn btn-green" type="button" onClick={() => setAppointmentOpen(true)}>BOOK APPOINTMENT <b>→</b></button></div><div className="hero-trust"><span><b>01</b><small>Current market-based rates</small></span><span><b>02</b><small>Physical assessment at PKV</small></span><span><b>03</b><small>No hidden charges</small></span></div></div><div className={`hero-media ${heroMediaStyles.media}`}><img src="/images/gold-assessment-daylight.png" alt="Gold pieces arranged for a careful valuation" /><div className="hero-media-label">GOLD / ASSESSMENT / 01</div><div className="hero-media-caption">WE VALUE WHAT YOU ALREADY OWN</div></div></section>
      <section className="value-section section-pad" id="value" data-calculator-scene><div className="section-intro"><p className="kicker">01 / KNOW YOUR VALUE</p><h2>Know your <em>value.</em></h2><p>Start with an indicative estimate before you visit. See the relationship between today’s rate, purity and weight in a way that is easy to follow.</p><a className="text-link" href="#calculator">BEGIN YOUR ESTIMATE <b>→</b></a></div><div className="calculator-panel" id="calculator"><div className="calc-top"><span>INDICATIVE ESTIMATE</span><span className="status"><i /> {rate === null ? 'CONNECTING TO RATE' : 'CURRENT PKV RATE'}</span></div><div className="calc-grid"><div><label className="field-label">PURITY / KARAT</label><div className="choice-row">{purityOptions.map((option) => <button key={option.karat} className={karat === option.karat ? 'choice active' : 'choice'} onClick={() => setKarat(option.karat)} aria-pressed={karat === option.karat}><b>{option.karat}K</b><small>{option.purity}% gold</small></button>)}</div><div className="weight-control"><div className="field-head"><label className="field-label" htmlFor="weight">WEIGHT IN GRAMS</label><output htmlFor="weight"><b>{weight.toFixed(1)}</b> g</output></div><input id="weight" type="range" min="0.5" max="150" step="0.1" value={weight} onChange={(event) => setWeight(Number(event.target.value))} /><input className="weight-number" aria-label="Weight in grams" type="number" min="0.5" max="150" step="0.1" value={weight} onChange={(event) => setWeight(Math.max(.5, Number(event.target.value) || .5))} /></div></div><div className="estimate"><span className="field-label">ESTIMATED GOLD VALUE</span><strong>{estimate === null ? '—' : `₹${formatIndianRupees(estimate)}`}</strong><div className="rate-line"><span>RATE / 24K GRAM</span><b>{rate === null ? 'Loading' : `₹${formatIndianRupees(rate)}`}</b></div><div className="breakdown"><span>{weight.toFixed(1)}g</span><b>×</b><span>₹{rate === null ? '—' : formatIndianRupees(rate)}</span><b>×</b><span>{selected.factor.toFixed(3)}</span></div><p>Formula: weight × current rate × purity factor. Indicative only; final value follows physical assessment.</p></div></div><a className="btn btn-green calc-cta" href="#contact">SPEAK WITH PKV GOLD <b>→</b></a></div></section>
      <section className="gold-forms section-pad" id="gold-we-value"><div className="section-intro split"><div><p className="kicker">02 / THE GOLD WE VALUE</p><h2>The gold<br />we <em>value.</em></h2></div><p>Not a catalogue. These are the forms of gold you may already own — and bring to PKV Gold for a clear assessment.</p></div><div className="category-grid">{jewelleryCategories.map((category) => <a className="category" key={category.id} href="#value"><div className="category-image"><img src={category.image} alt={`${category.label} brought for valuation`} /></div><div><span>{category.label}</span><small>We value what you already own.</small></div></a>)}</div></section>
      <section className="why section-pad"><div className="section-intro"><p className="kicker">03 / WHY PKV GOLD</p><h2>Value, made <em>clear.</em></h2><p>A professional process built around the information that matters to you.</p></div><div className="why-grid">{[['01','Best-Value Commitment','A fair, competitive valuation based on the details of your gold.'],['02','Transparent Assessment','We explain the rate, purity and weight behind the estimate.'],['03','Accurate Weight & Purity','The inputs are assessed carefully, with the final value visible.'],['04','Current Market-Based Rates','Your estimate starts with a rate managed for today’s market.'],['05','No Confusing Deductions','No unexplained line items or surprise charges in the conversation.'],['06','Professional Assistance','A clear, respectful experience from first enquiry to settlement.'],['07','Secure Handling','Your gold stays in a focused, professional assessment environment.'],['08','Clear Final Valuation','You understand the final number before deciding what comes next.']].map(([n,title,copy]) => <article className="why-card" key={n}><b>{n}</b><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
      <section className="process section-pad" id="process"><div className="section-intro"><p className="kicker">04 / HOW IT WORKS</p><h2>Five steps to a<br /><em>clear number.</em></h2><p>Every valuation happens in person at PKV Gold, with the important details kept visible.</p></div><div className="steps">{[['01','BRING','Bring your gold to PKV Gold.'],['02','MEASURE','We verify the net weight.'],['03','ASSESS','We assess purity and applicable value.'],['04','VALUE','We calculate using the current rate.'],['05','SETTLE','We explain the final value and proceed transparently.']].map(([n,title,copy]) => <article className="step" key={n}><span>{n}</span><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></section>
      <section className="statement section-pad"><p className="kicker">05 / THE PKV COMMITMENT</p><h2>You bring the gold.<br /><em>We bring the value.</em></h2><p>Our commitment is to give you a fair, competitive valuation based on the current applicable rate and the assessed purity and weight of your gold.</p><a className="btn btn-gold" href="#contact">START A CONVERSATION <b>→</b></a></section>
      <section className="explainer section-pad"><div><p className="kicker">06 / GOLD VALUE EXPLAINER</p><h2>The gold rate is<br /><em>not the final value.</em></h2><p>The rate is only the starting point. The final number is shaped by what is physically assessed.</p></div><div className="value-flow">{['Market rate','Purity','Net weight','Applicable valuation','Final amount'].map((item, index) => <div key={item}><span>{String(index + 1).padStart(2,'0')}</span><b>{item}</b>{index < 4 && <i>↓</i>}</div>)}</div></section>
      <section className="location section-pad" id="location"><div className="location-copy"><p className="kicker">08 / VISIT {contact.businessName.toUpperCase()}</p><h2>Come in.<br /><em>{contact.locationLabel}.</em></h2><p>Physical assessment happens at {contact.locationLabel}, where we can look at your gold carefully and answer your questions.</p><div className="location-details"><b>{contact.businessName.toUpperCase()}</b><span>{contact.address}</span><span>Opening hours: Please call ahead</span><span>{contact.displayPhone}</span></div><div className="location-actions"><a className="btn btn-green" href={contact.mapsUrl} target="_blank" rel="noreferrer">GET DIRECTIONS <b>→</b></a><ContactActions onAppointment={() => setAppointmentOpen(true)} compact /></div></div><div className="location-card"><LocationMap /><div className="map-caption"><span>{contact.businessName.toUpperCase()} / {contact.locationLabel.toUpperCase()}</span><small>Open in Google Maps for live directions.</small></div></div></section>
      <section className="contact section-pad" id="contact"><div><p className="kicker">09 / CONTACT PKV GOLD</p><h2>Speak with<br /><em>PKV Gold.</em></h2><p>Gold Buying · Valuation. A clear, private conversation about what your gold may be worth.</p><div className="contact-meta"><b>PKV GOLD</b><span>{contact.address}</span><span>{contact.displayPhone}</span></div><ContactActions onAppointment={() => setAppointmentOpen(true)} /></div><div className="contact-note"><span className="kicker">READY WHEN YOU ARE</span><h3>Bring your questions.<br /><em>Leave with clarity.</em></h3><p>WhatsApp us for a quick response, call directly, or book a visit at a time that works for you.</p><a className="text-link contact-text-link" href="#location">SEE THE LOCATION <b>→</b></a></div></section>
      <section className="faq section-pad" id="faq"><div className="section-intro"><p className="kicker">10 / QUESTIONS, ANSWERED</p><h2>Good to <em>know.</em></h2></div><div className="faq-list">{faqs.map(([question, answer], index) => <div className={`faq-item ${openFaq === index ? 'is-open' : ''}`} key={question}><button aria-expanded={openFaq === index} onClick={() => setOpenFaq(openFaq === index ? -1 : index)}><span>{question}</span><b>{openFaq === index ? '−' : '+'}</b></button>{openFaq === index && <p>{answer}</p>}</div>)}</div></section>
    </HeroValueTransition></main><footer className="footer"><div><b>PKV GOLD</b><span>Gold Buying • Valuation</span></div><nav><a href="#value">Know Your Value</a><a href="#gold-we-value">The Gold We Value</a><a href="#process">How It Works</a><a href="#location">Location</a><a href="#contact">Contact</a></nav><div><a href={`tel:${contact.phone}`}>Call PKV Gold</a><a href={buildGeneralWhatsAppUrl()} target="_blank" rel="noopener noreferrer">WhatsApp PKV Gold</a><span>{contact.address}</span></div><small>© 2026 PKV Gold</small></footer><AppointmentModal open={appointmentOpen} onClose={() => setAppointmentOpen(false)} />
    <FloatingContactActions />
  </div>;
}
