'use client';
import { FormEvent, useEffect, useRef, useState } from 'react';
import { buildAppointmentWhatsAppUrl } from '@/lib/constants';
type FormErrors = Partial<Record<'name' | 'location' | 'date', string>>;
export function AppointmentModal({ open, onClose }: { open: boolean; onClose: () => void }) {
  const closeRef = useRef<HTMLButtonElement>(null); const openerRef = useRef<HTMLElement | null>(null);
  const [errors, setErrors] = useState<FormErrors>({}); const [minDate, setMinDate] = useState('');
  useEffect(() => { setMinDate(new Date().toISOString().split('T')[0]); }, []);
  useEffect(() => { if (!open) return; setErrors({}); openerRef.current = document.activeElement as HTMLElement; closeRef.current?.focus(); const onKeyDown = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); }; document.addEventListener('keydown', onKeyDown); document.body.style.overflow = 'hidden'; return () => { document.removeEventListener('keydown', onKeyDown); document.body.style.overflow = ''; openerRef.current?.focus(); }; }, [open, onClose]);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const values = { name: String(data.get('name') || '').trim(), location: String(data.get('location') || '').trim(), date: String(data.get('date') || ''), remarks: String(data.get('remarks') || '').trim() }; const nextErrors: FormErrors = {}; if (!values.name) nextErrors.name = 'Please enter your name.'; if (!values.location) nextErrors.location = 'Please enter your location.'; if (!values.date) nextErrors.date = 'Please choose a preferred date.'; else if (minDate && values.date < minDate) nextErrors.date = 'Please choose today or a future date.'; setErrors(nextErrors); if (Object.keys(nextErrors).length) return; window.location.href = buildAppointmentWhatsAppUrl(values); }
  if (!open) return null;
  return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><div className="appointment-modal" role="dialog" aria-modal="true" aria-labelledby="appointment-title"><div className="modal-heading"><div><p className="kicker">PRIVATE VISIT / PKV GOLD</p><h2 id="appointment-title">Book your <em>appointment.</em></h2><p>Share the essentials and we&apos;ll confirm a suitable time on WhatsApp.</p></div><button className="modal-close" type="button" onClick={onClose} ref={closeRef} aria-label="Close appointment form">&times;</button></div><form className="appointment-form" onSubmit={submit} noValidate><label htmlFor="appointment-name">Name<input id="appointment-name" name="name" required autoComplete="name" placeholder="Your name" aria-invalid={Boolean(errors.name)} aria-describedby={errors.name ? 'appointment-name-error' : undefined} />{errors.name && <small id="appointment-name-error" className="field-error">{errors.name}</small>}</label><label htmlFor="appointment-location">Location<input id="appointment-location" name="location" required defaultValue="Kolathur, Chennai" placeholder="Your location" aria-invalid={Boolean(errors.location)} aria-describedby={errors.location ? 'appointment-location-error' : undefined} />{errors.location && <small id="appointment-location-error" className="field-error">{errors.location}</small>}</label><label htmlFor="appointment-date">Preferred date<input id="appointment-date" name="date" type="date" required min={minDate} aria-invalid={Boolean(errors.date)} aria-describedby={errors.date ? 'appointment-date-error' : undefined} />{errors.date && <small id="appointment-date-error" className="field-error">{errors.date}</small>}</label><label htmlFor="appointment-remarks">Remarks <span className="optional">Optional</span><textarea id="appointment-remarks" name="remarks" rows={3} placeholder="Anything you would like us to know?" /></label>{Object.keys(errors).length > 0 && <p className="form-error" role="alert">Please check the highlighted fields before continuing.</p>}<button className="btn btn-gold" type="submit">BOOK AN APPOINTMENT <b>&rarr;</b></button></form></div></div>;
}
